version: '3.8'
services:
  database:
    # container_name: db.deeporigin.com.br
    image: postgres:17
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=deeporigin
    ports:
      - '5432:5432'
    networks:
      - deeporigin_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - deeporigin_postgres_data:/var/lib/postgresql/data

volumes:
  deeporigin_postgres_data:

networks:
  deeporigin_network:
    driver: bridge
